### ISSUE TITLE
Images for Twitter objects not displaying on live site

### ISSUE THREAD

**Issue by OscarRobertRodriguez** [OscarRobertRodriguez/developerNews#45]
```css
.media-object-twitter .tw-user-img-contain {
    width: 50px;
    height: 50px;
    overflow: hidden;
// the assets does not need the ' / '  in front will through error and not display 
    background-image: url("/assets/images/meTest.jpg");
    background-size: cover
}
```
